baseURL = "https://oxpecker.netlify.app"
languageCode = "en-us"
title = "Oxpecker"

[menu]
[[menu.main]]
  name = 'Introduction'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Folder Structure'
  url = '/documentation/structure/'
  weight = 3
[[menu.main]]
  name = 'Commands'
  url = '/documentation/commands/'
  weight = 4
  [[menu.main]]
    name = 'Build'
    url = '/documentation/commands/build'
    parent = 'Commands'
    weight = 5
  [[menu.main]]
    name = 'Database'
    url = '/documentation/commands/database'
    parent = 'Commands'
    weight = 6
  [[menu.main]]
    name = 'Task'
    url = '/documentation/commands/task'
    parent = 'Commands'
    weight = 7
  [[menu.main]]
    name = 'Generate'
    url = '/documentation/commands/generate'
    parent = 'Commands'
    weight = 8
  [[menu.main]]
    name = 'Version'
    url = '/documentation/commands/version'
    parent = 'Commands'
    weight = 9
  [[menu.main]]
    name = 'Help'
    url = '/documentation/commands/help'
    parent = 'Commands'
    weight = 10
  [[menu.main]]
    name = 'Fix'
    url = '/documentation/commands/fix'
    parent = 'Commands'
    weight = 11
[[menu.main]]
  name = 'Plugins'
  url = '/documentation/plugins/'
  weight = 5
[[menu.main]]
  name = 'Changelog'
  url = '/documentation/changelog'
  weight = 6
